### ISSUE TITLE
tests on R 3.4 raises extra warning

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#7099]
https://rdatatable.gitlab.io/data.table/web/checks/data.table/test-lin-ancient-cran/00check.log

latest master

```
* checking tests ... OK
  Running ‘autoprint.R’
  Comparing ‘autoprint.Rout’ to ‘autoprint.Rout.save’ ...17,20d16
<        a
<    <int>
< 1:     1
< 2:     3
27,30d22
<        a
<    <int>
< 1:     1
< 2:     3
32,36d23
< Index: <a>
<        a
<    <int>
< 1:     1
< 2:     3
38,42d24
< Index: <a>
<        a
<    <int>
< 1:     1
< 2:     3
60,63d41
<        a
<    <int>
< 1:     1
< 2:     5
65,68d42
<        a
<    <int>
< 1:     1
< 2:     6
72,75d45
<        a
<    <int>
< 1:     1
< 2:     5
142,144d111
<        a
<    <int>
< 1:     9
150,153d116
<        a
<    <int>
< 1:    10
< 2:    10
155,158d117
<        a
<    <int>
< 1:    10
< 2:    10
160,163d118
<        a
<    <int>
< 1:    10
< 2:    10
209,214d163
<        x     y
<    <num> <num>
< 1:     1     1
< Warning message:
< In `[.data.table`(dt, , `:=`(y, 1)) :
<   A shallow copy of this data.table was taken so that := can add or remove 1 columns by reference. At an earlier point, this data.table was copied by R (or was created manually using structure() or similar). Avoid names<- and attr<- which in R currently (and oddly) may copy the whole data.table. Use set* syntax instead to avoid copying: ?set, ?setnames and ?setattr. It's also not unusual for data.table-agnostic packages to produce tables affected by this issue. If this message doesn't help, please report your use case to the data.table issue tracker so the root cause can be fixed or this message improved.
```

**Comment by MichaelChirico** [comment]
First guess is it's due to #6631. Unfortunately codespaces is not cooperating so I won't be able to install 3.4 to debug further.

I guess here:

```
dt = data.table(x = 1)
class(dt) = c("foo", "data.table", "data.frame")
dt[, y := 1]
```

`class<-` has created the shallow copy -- isn't this warning expected in that case? Possibly we should just ignore this issue as WAI.

**Comment by jangorecki** [comment]
That was a good guess. We fixed the warning. Printing, when it shouldn't, is still an issue, but till nobody reports that, I think it is fine to close. This really affects very few users (R 3.4.0 is very old) and it is only a printing behavior that is different.
Sooner or later we will move stated dependency to R 3.5.0 and then it will not be relevant at all.

**Comment by MichaelChirico** [comment]
Maybe confirm it's not present on 3.5.0 first? (offhand I don't recall we have ongoing CI for that)

(edir: just saw your comment to similar effect on the PR)

**Comment by aitap** [comment]
Both 3.4.0 and 3.5.0 warn about non-suppressed auto-printing and (with sufficiently old `knitr` installed) fail to rebuild vignette output due to [a `|>` pipe in `datatable-intro.Rmd`](https://github.com/Rdatatable/data.table/blob/05c7c68eea80a1df48fecbf812df2c99d513177a/vignettes/datatable-intro.Rmd#L662).

`3.4.0` additionally fails `datatable-benchmarking.Rmd` due to missing `isFALSE` and the new tests from #5401 due to missing ALTREP. Which one of these need fixing?

**Comment by MichaelChirico** [comment]
> `3.4.0` additionally fails `datatable-benchmarking.Rmd` due to missing `isFALSE` and the new tests from [#5401](https://github.com/Rdatatable/data.table/pull/5401) due to missing ALTREP. Which one of these need fixing?

Hm that's strange, could you share the exact errors & repro environments?

We define `isFALSE` here:

https://github.com/Rdatatable/data.table/blob/4773ef9d7d15c6d2611ec892aa1caa1b0a8e37e0/R/utils.R#L9-L12

Here's the 3.5.0 tag which includes `isFALSE`:

https://github.com/wch/r-source/blob/88de3c2999d72e257670deb5216acf3a426586b9/src/library/base/R/identical.R#L34

And we define a placeholder `ALTREP` macro here:

https://github.com/Rdatatable/data.table/blob/4773ef9d7d15c6d2611ec892aa1caa1b0a8e37e0/src/data.table.h#L5-L6

At the time, `ALTREP` was defined in Rinternals.h, though it's since moved to Defn.h (as of 4.2.0), maybe that matters?

https://github.com/wch/r-source/blob/88de3c2999d72e257670deb5216acf3a426586b9/src/include/Rinternals.h#L318

https://github.com/wch/r-source/blob/775760668cadaf563fe771960c8a4cb1f5d8e75c/src/include/Defn.h#L212

**Comment by aitap** [comment]
Sorry for being insufficiently precise regarding ALTREP: the tests were
failing due to the .Inspect() output differing from their expectations,
which has been fixed by #7125.

The remaining vignette problem is due to 'markdown' having an
undeclared dependency on R ≥ 3.5:

tools::buildVignette('00_pkg_src/data.table/vignettes/datatable-benchmarking.Rmd')
# Error in isFALSE(options[["standalone"]]) : 
#   could not find function "isFALSE"
traceback()
# 5: mark(..., format = "html", template = template)
# 4: markdown::mark_html(out, output, ...)
# 3: (if (grepl("\\.[Rr]md$", file)) knit2html else if
# (grepl("\\.[Rr]rst$", file)) knit2pandoc else knit)(file, encoding =
# encoding, quiet = quiet, envir = globalenv(), ...)
# 2: engine$weave(file, quiet = quiet, encoding = encoding, ...)
# 1: tools::buildVignette("00_pkg_src/data.table/vignettes/datatable-benchmarking.Rmd")

There probably exists a consistent set of package versions that really
does work on R-3.4, but it's not trivial to find. Older 'markdown'
needs older 'xfun' (for isFALSE), which requires downgrading 'knitr'
further, and so on.

**Comment by MichaelChirico** [comment]
> Please note that this package is no lo#6584 actively developed.

I guess we should pin our hopes on #6584 then  cc @ben-schwen

**Comment by jangorecki** [comment]
On 3.4 we should then skip building and testing vignettes

**Comment by aitap** [comment]
That's what we already do on GitLab CI. I'm sorry for the false alarm. I thought I found a [relatively easy way](https://paste.debian.net/hidden/54ddbb65/) to install compatible older package versions from the CRAN archive and missed the fact that the `isFALSE` failure was from `markdown`, not `data.table`.

**Comment by MichaelChirico** [comment]
Just chiming in to the original issue -- indeed we still get the minor output difference in 3.5.0.

**Comment by ben-schwen** [comment]
No warning on [3.5 anymore](https://rdatatable.gitlab.io/data.table/web/checks/data.table/test-lin-rel-vanilla/00check.log) so I'm closing here

**Comment by aitap** [comment]
Unfortunately, the NOTE is present in the [ancient](https://r-datatable.com/web/checks/data.table/test-lin-ancient-cran/00check.log) check output. The reason is due to how R-3.4 and R-3.5 auto-printed values: the thing on the call stack is not a call to `base::print`, but a promise object that evaluates to it:

```
R-3.5.0> debugonce(data.table:::shouldPrint)
R-3.5.0> data.table::as.data.table(mtcars)[, foo := "bar"]
debugging in: shouldPrint(x)
debug: {
    ret = (identical(.global$print, "") || address(x) != .global$print)
    .global$print = ""
    ret
}
Browse[2]> sys.calls()
[[1]]
function (x, ...) 
UseMethod("print")(x)

[[2]]
print.data.table(x)

[[3]]
shouldPrint(x)

Browse[2]> .Internal(inspect( sys.calls()[[1]] ))
@56251178d590 06 LANGSXP g0c0 []
  @56250f1d9530 05 PROMSXP g0c0 [MARK,NAM(1)]
  @56250f1548e8 01 SYMSXP g0c0 [MARK,NAM(3)] "x"
Browse[2]> identical(sys.calls()[[1]][[1]], base::print)
[1] FALSE
Browse[2]> typeof(sys.call(1)[[1]])
[1] "promise"
Browse[2]> identical(eval(sys.call(1)[[1]]), base::print)
[1] TRUE
```

whereas in modern R it's

```
Browse[2]> .Internal(inspect(sys.calls()[[1]]))
@5613ddcb89d0 06 LANGSXP g0c0 [REF(1)] 
  @5613dd97b600 03 CLOSXP g0c0 [REF(5)]
  FORMALS:
    @5613dd97b5c8 02 LISTSXP g0c0 [REF(1)] 
      TAG: @5613db452f38 01 SYMSXP g0c0 [MARK,REF(65535)] "x"
      @5613db3ed5e0 01 SYMSXP g0c0 [MARK,REF(6656)] "" (has value)
      TAG: @5613db3ed110 01 SYMSXP g0c0 [MARK,REF(65535)] "..."
      @5613db3ed5e0 01 SYMSXP g0c0 [MARK,REF(6656)] "" (has value)
  BODY:
    @5613dd97b558 21 BCODESXP g0c0 [REF(1)] 
  CLOENV:
    @5613db425480 04 ENVSXP g0c0 [MARK,REF(65535),LCK,gp=0x4000] <namespace:base>
  @5613db452f38 01 SYMSXP g0c0 [MARK,REF(65535)] "x"
Browse[2]> identical(sys.calls()[[1]][[1]], base::print)
[1] TRUE
```

In theory, the fix is to add another condition: if R version is within range (TODO: find out when it changed) and there's a promise on the call stack, and `eval(promise)` is `base::print`, then we're being auto-printed. Since it's the upstream call, evaluating the promise _should_ return its cached value, not run any more code.

**Comment by gitstopher** [comment]
Is this issue still open? Me and my group would like to try and contribute to the project and fix the issue.

**Comment by prestonimus** [comment]
Hi there! I am part of the group working on this issue, but we are having some problems getting to the actual root of the problem. Would it be appropriate for this to simply suppress the calls, or is there anything you might recommend?

**Comment by aitap** [comment]
Yes, the idea is to suppress the calls so that `tests/autoprint.R` produces the same output as in the "golden" file `tests/autoprint.Rout` on all supported versions of R (3.5-4.7). The root of the problem is that our current kludge doesn't work on R-3.4 and R-3.5 (and maybe other versions as well) due to differences in what `print.data.table` [observes on the call stack](https://github.com/Rdatatable/data.table/issues/7099#issuecomment-4049942066).

<details>
<summary>In case you're curious,</summary>

...the difference is due to R-3.5 [using `findVar` to locate `base::print`](https://github.com/r-devel/r-svn/blob/ab060c4e2c3c80c95434ac61a489ff40e20cc4fc/src/main/print.c#L991), which returns a promise, while modern R [uses `findFun`](https://github.com/r-devel/r-svn/blob/e701b3231bb0c6c0f3859fe83160b54ee375a7df/src/main/print.c#L372), which [extracts the value of the promise](https://github.com/r-devel/r-svn/blob/e701b3231bb0c6c0f3859fe83160b54ee375a7df/src/main/envir.c#L1910-L1921) before returning the function. The promise appears because when R [starts up](https://github.com/r-devel/r-svn/blob/acb57cb8ab0b38da8ed8fabee7bb135e72c98b51/src/main/main.c#L1058), it [populates](https://github.com/r-devel/r-svn/blob/acb57cb8ab0b38da8ed8fabee7bb135e72c98b51/src/library/base/baseloader.R#L79) the "base namespace" [using `makeLazy`](https://github.com/r-devel/r-svn/blob/acb57cb8ab0b38da8ed8fabee7bb135e72c98b51/src/main/builtin.c#L125).

</details>

If you can account for these differences so that printing is suppressed both in old and modern versions of R, that would be very good.
